[package]
name = "stablecoin"
version = "0.0.0"


[addresses]
stablecoin = "_"
master_minter = "_"
minter = "_" 
pauser = "_"
denylister = "_"

[dev-addresses]
stablecoin = "0xcafe"
master_minter = "0xbab"
minter = "0xface"
pauser = "0xdafe"
denylister = "0xcade"

[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"